### ISSUE TITLE
copy unexported field 

### ISSUE THREAD

**Issue by ZhijiaYang** [mohae/deepcopy#7]
is there method to deep copy unexported field in struct?

**Comment by mohae** [comment]
Sorry, no. If I recall correctly, attempting to set an unexported field using package reflect will result in a panic. 

The copying of unexported fields is something that would probably best be done with a Copy method on your struct.

**Comment by ZhijiaYang** [comment]
thank you, you are right.  I have read your code, and try to copy unexported field, but I failed. Just like you said, all I need  is one clone method on my struct.
